title: sonya-c 
email: hello@sonya-c.com.co 
description: Hello, I'm sonya 
baseurl: "" 
url: ""
twitter_username: ""
github_username: sonya-c 

# Build settings
plugins:
  - jekyll-feed

sass:
  sass_dir: _sass
  style: compressed

include: ['en', 'es']

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
